### ISSUE TITLE
Entire app white

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [GregVido/MicaDiscord#1]
![圖片](https://github.com/GregVido/MicaDiscord/assets/74187631/a7ed8405-8104-4f0b-8aee-ab2ac5c5003f)

**Comment by GregVido** [comment]
Thank you for reporting this bug to me, I'll fix it as soon as possible.

**Comment by IdkWhatToCallMe123** [comment]
Coming in here maybe a little bit late but I found out that this only happens when you have custom windows themes.
