### ISSUE TITLE
Stuck on Killing Discord

### ISSUE THREAD

**Issue by doejohn02** [GregVido/MicaDiscord#2]
As the title say, when I press the button ''Install'', all I get is a blinking > Killing Discord.

How do I fix this?

**Comment by GregVido** [comment]
Hi, there are two installers, have you tried both?

MicaDiscord-1.1.7-setup.exe
MicaDiscord-1.1.7.exe

**Comment by doejohn02** [comment]
I have tried both yes. Same issue persists on both of the installers unfortunately. Any idea how to solve this? I'd really love to use the amazing theme of yours.

**Comment by GregVido** [comment]
No, I tested on another PC, I had the same error but when I installed for all users with MicaDiscord-1.1.7-setup.exe, it worked. I will look more closely at this tomorrow because today I am not at home.

**Comment by doejohn02** [comment]
I'll try that aswell when I come home today, and get back to you here if it works.

**Comment by GregVido** [comment]
I just did a new update, it's now fixed
